### ISSUE TITLE
automate releases of e2e-harness binary

### ISSUE THREAD

**Issue by fgimenez** [giantswarm/e2e-harness#16]
We need to build and upload a new binary from the project after each merge to master and successful test execution. A good example is architect, this is the CI setup https://github.com/giantswarm/architect/blob/master/circle.yml (note that this is a 1.0 config and we use 2.0 in this repo), and this the script used for doing the release https://github.com/giantswarm/architect/blob/master/github-release.sh it would be nice to adapt it to be used in this repo.

**Comment by indyfree** [comment]
done: https://github.com/giantswarm/e2e-harness/pull/17
